import type { Student } from "../engine/types";
// Entirely invented teaching fixtures. Phone and identity-shaped values are synthetic, not contacts.
const names = [
  "林知禾",
  "周星原",
  "陈晨",
  "陆书宁",
  "沈以安",
  "许南乔",
  "方沐言",
  "宋景初",
  "叶明溪",
  "苏予宁",
  "江望舒",
  "顾清和",
  "唐星野",
  "何知远",
  "白云舟",
  "夏听澜",
  "程亦川",
  "温若竹",
  "邵语棠",
  "郝安然",
  "余向晚",
  "罗书予",
  "严牧之",
  "池映山",
  "梁新雨",
  "袁乐之",
  "孟初晴",
  "钟云帆",
  "秦墨川",
  "陶向宁",
];
export const demoStudents: Student[] = names.map((name, index) => ({
  id: `student:202600${String(index + 1).padStart(2, "0")}`,
  name,
  studentId: `202600${String(index + 1).padStart(2, "0")}`,
  className: index < 15 ? "2025级虚构信息技术1班" : "2025级虚构电子商务2班",
  phone: `1390000${String(index + 1).padStart(4, "0")}`,
  dorm: `${index < 15 ? 1 : 2}栋${301 + (index % 5)}室`,
  email: `student${index + 1}@example.invalid`,
}));
export const demoScenarios = [
  {
    id: "study",
    title: "学业 / 考勤",
    description: "迟到、成绩变化、升学意愿与联系方式",
    fileName: "虚构案例-学业考勤.txt",
    task: "study" as const,
    level: "L2" as const,
    text: "【全部为虚构演示材料】\n2026年3月15日，与2025级虚构信息技术1班陈晨（学号20260003，手机号13900000003）谈话。陈晨为大二学生，近期三周迟到3次，两门课程成绩下降，目前同时准备技能竞赛，并表达过专升本意愿。宿舍1栋303室。下次需了解时间安排。",
  },
  {
    id: "family",
    title: "家庭经济困难",
    description: "详细住址、具体家庭事件与资助核实",
    fileName: "虚构案例-家庭支持.txt",
    task: "talk" as const,
    level: "L2" as const,
    text: "【全部为虚构演示材料】\n林知禾，学号20260001，家庭地址：浙江省绍兴市虚构区示例路18号。父亲近期失业，学生表达生活开支压力。2026年4月12日约谈，先核实可申请的资助渠道，不推测家庭收入。",
  },
  {
    id: "health",
    title: "心理健康相关",
    description: "诊断表述最小化，只整理事实与待核实问题",
    fileName: "虚构案例-健康支持.txt",
    task: "talk" as const,
    level: "L2" as const,
    text: "【全部为虚构演示材料】\n周星原（20260002）自述确诊为焦虑症，近期希望调整学习安排。邮箱student2@example.invalid。请核实本人希望获得的支持；本工具不做心理诊断。",
  },
  {
    id: "career",
    title: "就业困难",
    description: "投递事实、实训表达与联系方式",
    fileName: "虚构案例-就业支持.txt",
    task: "career" as const,
    level: "L2" as const,
    text: "【全部为虚构演示材料】\n陆书宁，学号20260004，投递5份简历，收到1次面试邀请。希望了解如何描述实训经历。联系电话13900000004。",
  },
  {
    id: "upgrade",
    title: "专升本规划",
    description: "升学目标、每周时间与待核实要求",
    fileName: "虚构案例-专升本规划.txt",
    task: "career" as const,
    level: "L1" as const,
    text: "【全部为虚构演示材料】\n陈晨，学号20260003，计划准备专升本；每周可安排6小时复习，需先核实目标专业与考试要求。",
  },
];
export const demoRosterRows = [
  ["姓名", "学号", "班级", "手机号", "宿舍", "邮箱"],
  ...demoStudents.map((s) => [
    s.name,
    s.studentId,
    s.className,
    s.phone!,
    s.dorm!,
    s.email!,
  ]),
];
export const demoAttendance = [
  ["姓名", "学号", "近三周迟到次数"],
  ...demoStudents.map((s, i) => [
    s.name,
    s.studentId,
    String(i === 2 ? 3 : i % 2),
  ]),
];
export const demoGrades = [
  ["姓名", "学号", "课程A上次", "课程A本次", "课程B上次", "课程B本次"],
  ...demoStudents.map((s, i) => [
    s.name,
    s.studentId,
    "80",
    String(i === 2 ? 68 : 78 + (i % 10)),
    "82",
    String(i === 2 ? 70 : 80 + (i % 9)),
  ]),
];

export const demoClassAnalysis = [
  [
    "姓名",
    "学号",
    "较早成绩",
    "上次成绩",
    "本次成绩",
    "前4周迟到",
    "近4周迟到",
    "前4周旷课",
    "近4周旷课",
    "近4周请假",
    "实训异常",
    "实习异常",
  ],
  ...demoStudents.map((student, index) => [
    student.name,
    student.studentId,
    String(82 - (index % 5)),
    String(index === 2 ? 74 : 80 - (index % 4)),
    String(index === 2 ? 58 : index === 6 ? 55 : 79 - (index % 6)),
    String(index % 2),
    String(index === 2 ? 4 : index === 8 ? 3 : index % 2),
    "0",
    String(index === 2 ? 2 : index === 11 ? 2 : 0),
    String(index === 15 ? 3 : index % 2),
    index === 6 ? "缺席一次" : "正常",
    index === 20 ? "未到岗" : "正常",
  ]),
];
